# Generated by Django 5.0.2 on 2024-03-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cdob', models.CharField(max_length=15)),
                ('ccity', models.CharField(max_length=50)),
                ('caddress', models.CharField(max_length=500)),
                ('ccontact', models.CharField(max_length=15)),
                ('cnationality', models.CharField(max_length=20)),
                ('cdateincident', models.CharField(max_length=20)),
                ('clocation', models.CharField(max_length=100)),
                ('cdetails', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'use',
            },
        ),
    ]
