# Generated by Django 4.2.2 on 2024-06-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a_r',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='charge_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('law', models.CharField(blank=True, max_length=100, null=True)),
                ('officer', models.CharField(blank=True, max_length=100, null=True)),
                ('investigation', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'charge_sheet',
            },
        ),
    ]
