# Generated by Django 4.2.2 on 2024-06-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_a_r_charge_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='a_r',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
