# Generated by Django 4.2.2 on 2024-06-17 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_user_a_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge_sheet',
            name='user',
        ),
        migrations.AddField(
            model_name='charge_sheet',
            name='a_r',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge_sheet',
            name='user_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
