# Generated by Django 4.2.2 on 2024-06-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_charge_sheet_user_charge_sheet_a_r_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge_sheet',
            old_name='a_r',
            new_name='t_f',
        ),
    ]
