# Generated by Django 4.2.2 on 2024-06-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_a_r_charge_sheet_t_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge_sheet',
            name='user_a',
        ),
        migrations.AddField(
            model_name='user',
            name='user_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.charge_sheet'),
        ),
    ]
