# Generated by Django 4.2.2 on 2024-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_charge_sheet_user_a_user_user_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_sheet',
            name='t_f',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
