# Generated by Django 4.2.2 on 2024-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_charge_sheet_t_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge_sheet',
            name='t_f',
            field=models.BooleanField(default=False),
        ),
    ]
