# Generated by Django 4.2.2 on 2024-06-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_charge_sheet_main_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_c',
        ),
        migrations.AlterField(
            model_name='charge_sheet',
            name='main_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
